# Generated by Django 4.2.24 on 2025-09-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер рабочего места')),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
            },
        ),
    ]
